"""Performance-evaluation templates, seeded from the FY26 appraisal workbooks.

Each template is the parameter grid for one role: an ordered list of parameters
with a weight, summing to exactly 100. A template is matched to an employee by
(designation, department) -- designation alone is NOT enough, because the
designation list is a rank ladder, not a function. Two people can both be
"Assistant Manager" and need completely different forms (Anuj is Ops Support,
Shivani is HR), and two can both be "Executive" (Bhaskar is Admin, Pratik is IT).
Department is what separates them. An employee can also carry an explicit
pe_template_key that overrides the match entirely.

Narrative form: everyone EXCEPT Field Officers answers 7 questions. Q1-Q6 are
common; Q7 differs between field and head-office staff.
"""

# The 7 narrative questions. Only Q7 differs between the two variants.
NARRATIVE_QUESTIONS = {
    "field": [
        'What do you understand about your responsibilities in the company?',
        'What do you expect to be the biggest challenge in your role?',
        'Are you able to complete your work accurately and on time?',
        'Are you open to changes in processes, technology, or work requirements?',
        'How do you rate your overall performance during this review period, and what key areas do you think you should improve in the next cycle?',
        'How do you align your personal goals with company objectives?',
        'Give suggestions and comments to improve the culture at Radhya.',
    ],
    "ho": [
        'What do you understand about your responsibilities in the company?',
        'What do you expect to be the biggest challenge in your role?',
        'Are you able to complete your work accurately and on time?',
        'Are you open to changes in processes, technology, or work requirements?',
        'How do you rate your overall performance during this review period, and what key areas do you think you should improve in the next cycle?',
        'How do you align your personal goals with company objectives?',
        'What extra responsibilities have you taken on during this period?',
    ],
}

NARRATIVE_QUESTIONS_HI = {
    # Hindi is shown ALONGSIDE English (never instead of it) on the Field Officer
    # form. FOs filled the paper version in Hindi -- see the scanned "FO Self" forms.
    "field": [
        'कंपनी में आपकी ज़िम्मेदारियों के बारे में आप क्या समझते हैं?',
        'आपके अनुसार आपके काम में सबसे बड़ी चुनौती क्या रहेगी?',
        'क्या आप अपना काम सही ढंग से और समय पर पूरा कर पाते हैं?',
        'क्या आप प्रक्रिया, तकनीक या काम की ज़रूरतों में होने वाले बदलावों के लिए तैयार रहते हैं?',
        'इस अवधि में आप अपने समग्र प्रदर्शन को कैसा आंकते हैं, और अगले चक्र में किन मुख्य क्षेत्रों में सुधार करना चाहेंगे?',
        'आप अपने व्यक्तिगत लक्ष्यों को कंपनी के उद्देश्यों के साथ किस प्रकार जोड़ते हैं?',
        'राध्या में कार्य-संस्कृति बेहतर बनाने के लिए अपने सुझाव और टिप्पणियाँ दें।',
    ],
}

# Grade bands, from the printed table on the PE sheet:
#   <=30 C | 31-49 B | 50-69 B+ | 70-89 A | 90-100 A+
# NOTE: the sheet's own formula used `<30` for C, contradicting its printed table,
# so a score of exactly 30 graded as B. The printed table wins here.
GRADE_BANDS = [
    (30, "C", "Unsatisfactory"),
    (49, "B", "Average"),
    (69, "B+", "Good"),
    (89, "A", "Very Good"),
    (100, "A+", "Excellent"),
]

PE_TEMPLATES = [
    {
        "key": 'field-divisional-manager',
        "name": 'Divisional Manager',
        "narrative": 'field',
        "applies_to": [
            {"designation": 'Divisional Manager', "department": 'Operations'},
            # Area Manager has no sheet of its own in the FY26 workbooks; it shares the
            # Divisional Manager grid by decision, not by omission.
            {"designation": 'Area Manager', "department": 'Operations'},
        ],
        "parameters": [
            {"seq": 1, "weight": 15,
             "name": 'Business Growth',
             "description": 'Overall growth of all branches (disbursement + clients)',
             "tool": 'Growth %'},
            {"seq": 2, "weight": 12,
             "name": 'Collection Efficiency',
             "description": 'Ensures strong collection across division',
             "tool": 'Collection % report'},
            {"seq": 3, "weight": 12,
             "name": 'PAR Management',
             "description": 'Maintains PAR within limits',
             "tool": 'PAR report'},
            {"seq": 4, "weight": 10,
             "name": 'Disbursement Quality',
             "description": 'Ensures quality portfolio, low default',
             "tool": 'Audit & default ratio'},
            {"seq": 5, "weight": 12,
             "name": 'Branch Performance Monitoring',
             "description": 'Tracks BM & branch-wise performance',
             "tool": 'Target vs achievement'},
            {"seq": 6, "weight": 5,
             "name": 'GRT Quality & Monitoring',
             "description": 'Ensures proper GRT conduction, client understanding & fraud control',
             "tool": 'GRT checklist, audit findings, field verification'},
            {"seq": 7, "weight": 6,
             "name": 'Team Management & Leadership',
             "description": 'Manages and guides BMs effectively',
             "tool": 'HO feedback, attrition rate'},
            {"seq": 8, "weight": 5,
             "name": 'Field Monitoring & Branch Visits',
             "description": 'Regular visits & ground verification',
             "tool": 'Visit reports'},
            {"seq": 9, "weight": 5,
             "name": 'Audit & Compliance Control',
             "description": 'Ensures SOP adherence across branches',
             "tool": 'Audit score'},
            {"seq": 10, "weight": 5,
             "name": 'Policy Implementation',
             "description": 'Proper execution of policies',
             "tool": 'Review reports'},
            {"seq": 11, "weight": 3,
             "name": 'Operational Efficiency',
             "description": 'Smooth functioning of branches',
             "tool": 'Issue resolution TAT'},
            {"seq": 12, "weight": 2,
             "name": 'Reporting & MIS Accuracy',
             "description": 'Timely and accurate reporting',
             "tool": 'MIS tracking'},
            {"seq": 13, "weight": 2,
             "name": 'Coordination & Communication',
             "description": 'Coordination with HO & departments',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 6,
             "name": 'Extra Responsibilities',
             "description": 'Employee willingly takes additional responsibilities beyond assigned duties, supports in urgent tasks, and contributes to overall organizational goals.',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'field-branch-manager',
        "name": 'Branch Manager',
        "narrative": 'field',
        "applies_to": [
            {"designation": 'Branch Manager', "department": 'Operations'},
            {"designation": 'Senior Branch Manager', "department": 'Operations'},
        ],
        "parameters": [
            {"seq": 1, "weight": 15,
             "name": 'Branch Business Growth',
             "description": 'Overall growth in portfolio including disbursement and client base',
             "tool": 'Monthly branch report (Disbursement + Active clients growth %)'},
            {"seq": 2, "weight": 13,
             "name": 'Collection Efficiency',
             "description": 'Ensures high collection and controls overdue',
             "tool": 'Collection %, MIS Report'},
            {"seq": 3, "weight": 13,
             "name": 'PAR Management',
             "description": 'Maintains PAR within limits and controls delinquency',
             "tool": 'PAR Report (PAR % vs target)'},
            {"seq": 4, "weight": 10,
             "name": 'Disbursement Quality',
             "description": 'Ensures proper client selection and minimum defaults',
             "tool": 'Audit report, default ratio'},
            {"seq": 5, "weight": 10,
             "name": 'Team Productivity',
             "description": 'Ensures team achieves targets (FO-wise performance)',
             "tool": 'target vs achievement'},
            {"seq": 6, "weight": 5,
             "name": 'Field Monitoring & Visits',
             "description": 'Regular field visits, center meeting checks, staff monitoring',
             "tool": 'Visit tracker, surprise visit report'},
            {"seq": 7, "weight": 5,
             "name": 'Center Meeting Quality',
             "description": 'Ensures discipline and quality in center meetings',
             "tool": 'Random visit feedback, audit'},
            {"seq": 8, "weight": 5,
             "name": 'Documentation & Audit Compliance',
             "description": 'Ensures error-free documentation and audit readiness',
             "tool": 'Audit score, error count'},
            {"seq": 9, "weight": 5,
             "name": 'Policy & SOP Adherence',
             "description": 'Ensures all processes are followed strictly in branch',
             "tool": 'Audit remarks, violations'},
            {"seq": 10, "weight": 5,
             "name": 'Branch Hygiene & Discipline',
             "description": 'Maintains office discipline, attendance & punctuality',
             "tool": 'Attendance records, audit checklist'},
            {"seq": 11, "weight": 5,
             "name": 'Team Management & Leadership',
             "description": 'Leads, motivates and manages team effectively',
             "tool": 'Supervisor feedback, attrition rate'},
            {"seq": 12, "weight": 3,
             "name": 'Customer Handling & Grievance Resolution',
             "description": 'Ensures timely resolution of customer issues',
             "tool": 'Complaint register, resolution TAT'},
            {"seq": 13, "weight": 2,
             "name": 'Reporting & MIS Accuracy',
             "description": 'Ensures timely and accurate reporting to HO',
             "tool": 'Report submission timeliness & accuracy'},
            {"seq": 14, "weight": 4,
             "name": 'Extra Responsibilities',
             "description": 'Employee willingly takes additional responsibilities beyond assigned duties, supports in urgent tasks, and contributes to overall organizational goals.',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'field-field-officer',
        "name": 'Field Officer',
        # FOs DO answer the 7 questions -- they filled them on paper (the scanned
        # "FO Self" PDFs), which is why they have no tab in the assessment workbook.
        # Same field Q7 ("Give Suggestions & comments...") as BM/DM/Audit.
        "narrative": 'field',
        # FOs read Hindi -- their paper forms were filled in Hindi. Every parameter
        # and question carries a Hindi twin, shown UNDER the English, never instead.
        "bilingual": True,
        "applies_to": [
            {"designation": 'Field Officer', "department": 'Operations'},
            {"designation": 'Senior Field Officer', "department": 'Operations'},
        ],
        "parameters": [
            {"seq": 1, "weight": 10,
             "name": 'New Client Acquisition',
             "description": 'Adds new customers with proper quality checks',
             "name_hi": 'नए ग्राहक जोड़ना',
             "description_hi": 'गुणवत्ता जाँच के साथ नए ग्राहक जोड़ना',
             "tool": 'Monthly onboarding report'},
            {"seq": 2, "weight": 15,
             "name": 'Disbursement Target Achievement',
             "description": 'Achieves monthly disbursement targets',
             "name_hi": 'ऋण वितरण लक्ष्य की प्राप्ति',
             "description_hi": 'मासिक ऋण वितरण लक्ष्य पूरा करना',
             "tool": '(Actual ÷ Target) × 100'},
            {"seq": 3, "weight": 10,
             "name": 'Disbursement Quality',
             "description": 'Ensures proper verification to avoid future defaults',
             "name_hi": 'ऋण वितरण की गुणवत्ता',
             "description_hi": 'भविष्य में चूक से बचने के लिए उचित सत्यापन सुनिश्चित करना',
             "tool": 'Delinquency report / audit'},
            {"seq": 4, "weight": 17,
             "name": 'Collection Efficiency',
             "description": 'Ability to collect due amounts on time and maintain high collection performance',
             "name_hi": 'वसूली दक्षता',
             "description_hi": 'बकाया राशि समय पर वसूल करना और वसूली का उच्च स्तर बनाए रखना',
             "tool": '(Collection ÷ Due) × 100, MIS Report'},
            {"seq": 5, "weight": 10,
             "name": 'PAR Management',
             "description": 'Manages overdue accounts and prevents risk escalation and Regular follow-up with overdue customers for recovery',
             "name_hi": 'पीएआर (बकाया) प्रबंधन',
             "description_hi": 'बकाया खातों का प्रबंधन, जोखिम बढ़ने से रोकना और बकायादार ग्राहकों से नियमित फॉलो-अप',
             "tool": 'PAR % report, Visit tracking vs plan'},
            {"seq": 6, "weight": 5,
             "name": 'Daily Field Visit Efficiency',
             "description": 'Completes planned visits effectively',
             "name_hi": 'दैनिक फील्ड विज़िट दक्षता',
             "description_hi": 'नियोजित विज़िट प्रभावी ढंग से पूरी करना',
             "tool": 'Planned vs actual visits %'},
            {"seq": 7, "weight": 5,
             "name": 'Center Meeting Quality',
             "description": 'Conducts timely and effective center meetings',
             "name_hi": 'केंद्र बैठक की गुणवत्ता',
             "description_hi": 'समय पर और प्रभावी केंद्र बैठकें आयोजित करना',
             "tool": 'Attendance % / meeting records'},
            {"seq": 8, "weight": 5,
             "name": 'Documentation Accuracy',
             "description": 'Maintains complete and error-free documentation',
             "name_hi": 'दस्तावेज़ों की सटीकता',
             "description_hi": 'पूर्ण और त्रुटिरहित दस्तावेज़ बनाए रखना',
             "tool": 'Audit errors count'},
            {"seq": 9, "weight": 5,
             "name": 'Policy & SOP Adherence',
             "description": 'Follows company rules and processes strictly',
             "name_hi": 'नीति एवं एसओपी का पालन',
             "description_hi": 'कंपनी के नियमों और प्रक्रियाओं का कड़ाई से पालन करना',
             "tool": 'Audit remarks / violations'},
            {"seq": 10, "weight": 5,
             "name": 'Branch Hygiene, Attendance & Punctuality',
             "description": 'Maintains cleanliness and discipline at branch, ensures proper grooming, follows attendance rules, and reports to work and meetings on time regularly',
             "name_hi": 'शाखा स्वच्छता, उपस्थिति एवं समयबद्धता',
             "description_hi": 'शाखा में स्वच्छता और अनुशासन बनाए रखना, उचित वेशभूषा, उपस्थिति नियमों का पालन, और काम व बैठकों में समय पर पहुँचना',
             "tool": 'Attendance records, punctuality report, branch audit/inspection checklist'},
            {"seq": 11, "weight": 5,
             "name": 'Reliability / Dependability',
             "description": 'Consistently performs at a high level, manages time and workload effectively to meet responsibilities. The extent to which the employee can be depended upon to be available for work, to complete work properly, and to complete work on time.',
             "name_hi": 'विश्वसनीयता / भरोसेमंदता',
             "description_hi": 'लगातार अच्छा प्रदर्शन करना, समय और कार्यभार का प्रबंधन कर ज़िम्मेदारियाँ निभाना। कर्मचारी पर काम के लिए उपलब्ध रहने, काम सही ढंग से और समय पर पूरा करने के लिए कितना भरोसा किया जा सकता है।',
             "tool": 'Written oral communication is clear, organized, and effective. Listens and comprehends well, Appearance and behaviour that an individual displays in a professional environment(place of work)'},
            {"seq": 12, "weight": 3,
             "name": 'Customer Responsiveness',
             "description": 'The ability to analyze work, set goals, develop action plans, utilize time, and consider the amount of supervision required.',
             "name_hi": 'ग्राहक के प्रति तत्परता',
             "description_hi": 'काम का विश्लेषण करने, लक्ष्य तय करने, कार्य-योजना बनाने, समय का उपयोग करने और कितनी निगरानी की ज़रूरत है, इसे ध्यान में रखने की क्षमता।',
             "tool": 'How quickly and effectively the employee responds to customer queries and resolves complaints within the defined timeline'},
            {"seq": 13, "weight": 2,
             "name": 'Cooperation and Teamwork',
             "description": 'Respectful of colleagues when working with others and makes valuable contributions to help the group achieve its goals.',
             "name_hi": 'सहयोग और टीम भावना',
             "description_hi": 'साथियों के साथ काम करते समय सम्मानपूर्ण व्यवहार और समूह के लक्ष्य पूरे करने में सार्थक योगदान।',
             "tool": 'Measured through supervisor and peer feedback, focusing on the employee’s willingness to support colleagues and actively contribute to team goals.'},
            {"seq": 14, "weight": 3,
             "name": 'Extra Responsibilities',
             "description": 'Employee willingly takes additional responsibilities beyond assigned duties, supports in urgent tasks, and contributes to overall organizational goals.',
             "name_hi": 'अतिरिक्त ज़िम्मेदारियाँ',
             "description_hi": 'कर्मचारी सौंपे गए कार्यों से आगे बढ़कर स्वेच्छा से अतिरिक्त ज़िम्मेदारियाँ लेता है, ज़रूरी कामों में सहयोग करता है और कंपनी के समग्र लक्ष्यों में योगदान देता है।',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'risk-audit-manager',
        "name": 'Manager - Risk and Credit',
        "narrative": 'field',
        "applies_to": [
            # The Audit department was renamed Risk and Credit and the title dropped to
            # plain "Manager", so that pair is the live one (Ankit, RMF0022). The
            # "Audit Manager" designation still exists in the app's list, so it stays
            # mapped rather than silently becoming a dead end.
            #
            # CAUTION: "Manager" is a generic rank. A future Manager in Risk and Credit
            # doing CREDIT rather than audit work would land on this grid. Give them an
            # explicit pe_template_key instead of loosening this further.
            {"designation": 'Manager', "department": 'Risk and Credit'},
            {"designation": 'Audit Manager', "department": 'Risk and Credit'},
        ],
        "parameters": [
            {"seq": 1, "weight": 12,
             "name": 'GRT Quality & Accuracy',
             "description": 'Conducts proper GRT ensuring correct customer & group assessment',
             "tool": 'GRT audit score, field validation reports'},
            {"seq": 2, "weight": 12,
             "name": 'Customer Verification Accuracy',
             "description": 'Ensures correct verification of borrower identity & details',
             "tool": '% of discrepancies found in audit'},
            {"seq": 3, "weight": 12,
             "name": 'Group Formation Quality',
             "description": 'Ensures strong and reliable group formation',
             "tool": 'PAR/NPA trend of formed groups'},
            {"seq": 4, "weight": 10,
             "name": 'Risk Assessment Accuracy',
             "description": 'Identifies risky customers and avoids wrong approvals',
             "tool": '% of bad cases sourced'},
            {"seq": 5, "weight": 10,
             "name": 'Policy & SOP Adherence',
             "description": 'Follows credit policies, RBI norms & internal guidelines',
             "tool": 'Audit findings, compliance score'},
            {"seq": 6, "weight": 8,
             "name": 'TAT for GRT & Case Processing',
             "description": 'Completes GRT and case submission within timeline',
             "tool": 'TAT reports'},
            {"seq": 7, "weight": 8,
             "name": 'Field Discipline & Process Compliance',
             "description": 'Properly follows field process during center visits',
             "tool": 'Supervisor/field audit feedback'},
            {"seq": 8, "weight": 5,
             "name": 'Coordination with Ops & Branch',
             "description": 'Works effectively with ops team & branch staff',
             "tool": 'Feedback from BM/Ops'},
            {"seq": 9, "weight": 5,
             "name": 'Documentation Verification',
             "description": 'Ensures correct document collection & validation',
             "tool": 'Documentation audit score'},
            {"seq": 10, "weight": 5,
             "name": 'Fraud Detection & Prevention',
             "description": 'Identifies fake customers/groups during GRT',
             "tool": 'No. of fraud cases identified'},
            {"seq": 11, "weight": 5,
             "name": 'Productivity (Cases Handled)',
             "description": 'Number of GRTs/cases completed',
             "tool": 'Daily/monthly productivity report'},
            {"seq": 12, "weight": 2,
             "name": 'Process Improvement & Suggestions',
             "description": 'Suggests improvements in credit/GRT process',
             "tool": 'No. of suggestions implemented'},
            {"seq": 13, "weight": 2,
             "name": 'Discipline & Reliability',
             "description": 'Maintains punctuality, attendance, ownership',
             "tool": 'Attendance, supervisor feedback'},
            {"seq": 14, "weight": 2,
             "name": 'Extra Responsibilities',
             "description": 'Takes initiative beyond assigned duties',
             "tool": 'Management feedback'},
            {"seq": 15, "weight": 2,
             "name": 'Training & Team Support',
             "description": 'Supports training of field staff on credit norms',
             "tool": 'Management feedback'},
        ],
    },
    {
        # Derived from the Risk & Credit Manager grid -- there is no Credit Officer
        # sheet in the FY26 workbooks (the role postdates them). Tweaks vs that grid:
        #   dropped Training & Team Support (2)  -- a Credit Officer doesn't train staff
        #   Documentation Verification  5 -> 9   } the core of the job
        #   Risk Assessment Accuracy   10 -> 12  }
        #   Fraud Detection             5 -> 8
        #   Group Formation Quality    12 -> 8   -- more the audit/field lens than credit's
        #   Field Discipline            8 -> 6
        #   Process Improvement         2 -> 1
        "key": 'risk-credit-officer',
        "name": 'Credit Officer',
        "narrative": 'field',
        "applies_to": [
            {"designation": 'Credit Officer', "department": 'Risk and Credit'},
        ],
        "parameters": [
            {"seq": 1, "weight": 12,
             "name": 'GRT Quality & Accuracy',
             "description": 'Conducts proper GRT ensuring correct customer & group assessment',
             "tool": 'GRT audit score, field validation reports'},
            {"seq": 2, "weight": 12,
             "name": 'Customer Verification Accuracy',
             "description": 'Ensures correct verification of borrower identity & details',
             "tool": '% of discrepancies found in audit'},
            {"seq": 3, "weight": 12,
             "name": 'Risk Assessment Accuracy',
             "description": 'Identifies risky customers and avoids wrong approvals',
             "tool": '% of bad cases sourced'},
            {"seq": 4, "weight": 10,
             "name": 'Policy & SOP Adherence',
             "description": 'Follows credit policies, RBI norms & internal guidelines',
             "tool": 'Audit findings, compliance score'},
            {"seq": 5, "weight": 9,
             "name": 'Documentation Verification',
             "description": 'Ensures correct document collection & validation before sanction',
             "tool": 'Documentation audit score'},
            {"seq": 6, "weight": 8,
             "name": 'Fraud Detection & Prevention',
             "description": 'Identifies fake customers/groups during appraisal & GRT',
             "tool": 'No. of fraud cases identified'},
            {"seq": 7, "weight": 8,
             "name": 'TAT for GRT & Case Processing',
             "description": 'Completes GRT and case submission within timeline',
             "tool": 'TAT reports'},
            {"seq": 8, "weight": 8,
             "name": 'Group Formation Quality',
             "description": 'Ensures strong and reliable group formation',
             "tool": 'PAR/NPA trend of formed groups'},
            {"seq": 9, "weight": 6,
             "name": 'Field Discipline & Process Compliance',
             "description": 'Properly follows field process during center visits',
             "tool": 'Supervisor/field audit feedback'},
            {"seq": 10, "weight": 5,
             "name": 'Coordination with Ops & Branch',
             "description": 'Works effectively with ops team & branch staff',
             "tool": 'Feedback from BM/Ops'},
            {"seq": 11, "weight": 5,
             "name": 'Productivity (Cases Handled)',
             "description": 'Number of GRTs/cases completed',
             "tool": 'Daily/monthly productivity report'},
            {"seq": 12, "weight": 2,
             "name": 'Discipline & Reliability',
             "description": 'Maintains punctuality, attendance, ownership',
             "tool": 'Attendance, supervisor feedback'},
            {"seq": 13, "weight": 2,
             "name": 'Extra Responsibilities',
             "description": 'Takes initiative beyond assigned duties',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 1,
             "name": 'Process Improvement & Suggestions',
             "description": 'Suggests improvements in credit/GRT process',
             "tool": 'No. of suggestions implemented'},
        ],
    },
    {
        "key": 'ho-accounts-manager',
        "name": 'Accounts Manager',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Accounts Manager', "department": 'Accounts'},
        ],
        "parameters": [
            {"seq": 1, "weight": 15,
             "name": 'Book Closure & Timeliness',
             "description": 'Ensures timely monthly/quarterly book closure',
             "tool": 'Closing TAT vs deadline'},
            {"seq": 2, "weight": 15,
             "name": 'Accuracy of  Entries',
             "description": 'Maintains error-free accounting even during high workload or tight deadlines.',
             "tool": 'Audit errors, reconciliation issues'},
            {"seq": 3, "weight": 5,
             "name": 'Discipline & Reliability',
             "description": 'Follows company discipline including dress code, punctuality, and professional behavior',
             "tool": 'HR/ Management feedback'},
            {"seq": 4, "weight": 10,
             "name": 'Payroll Support',
             "description": 'Ensures timely and error-free salary calculation',
             "tool": 'Management feedback'},
            {"seq": 5, "weight": 10,
             "name": 'Audit & Compliance',
             "description": 'Supports internal/external audits and ensures no major observations',
             "tool": 'Management feedback'},
            {"seq": 6, "weight": 8,
             "name": 'MIS & Financial Reporting',
             "description": 'Prepares accurate and timely MIS reports for management',
             "tool": 'Report accuracy & submission TAT'},
            {"seq": 7, "weight": 5,
             "name": 'Data Management & Documentation',
             "description": 'Maintains proper records and documentation',
             "tool": 'Document audit, record completeness'},
            {"seq": 8, "weight": 5,
             "name": 'Coordination with Branches & Departments',
             "description": 'Ensures smooth coordination for financial data and issue resolution',
             "tool": 'Management feedback'},
            {"seq": 9, "weight": 4,
             "name": 'System Handling (Tally)',
             "description": 'Efficient use of accounting software',
             "tool": 'Management feedback'},
            {"seq": 10, "weight": 2,
             "name": 'Team Bonding & Support',
             "description": 'Maintains positive relationships and supports team members in work and deadlines.',
             "tool": 'Management feedback'},
            {"seq": 11, "weight": 7,
             "name": 'Loan Disbursement Accounting',
             "description": 'Proper accounting of loan disbursements',
             "tool": 'Disbursement records accuracy / mismatch cases'},
            {"seq": 12, "weight": 5,
             "name": 'Work Quality',
             "description": 'Maintains accuracy and quality of work',
             "tool": 'Error rate during peak time, HR /supervisor review'},
            {"seq": 13, "weight": 5,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 4,
             "name": 'Extra Responsibilities',
             "description": 'Employee willingly takes additional responsibilities beyond assigned duties, supports in urgent tasks, and contributes to overall organizational goals.',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'ho-admin-executive',
        "name": 'Executive - Administration',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Executive', "department": 'Administration'},
        ],
        "parameters": [
            {"seq": 1, "weight": 10,
             "name": 'Facility Management',
             "description": 'Ensures smooth functioning of office facilities (electricity, housekeeping, etc.)',
             "tool": 'employee feedback'},
            {"seq": 2, "weight": 8,
             "name": 'Asset Management',
             "description": 'Proper tracking and maintenance of office assets',
             "tool": 'Asset register'},
            {"seq": 3, "weight": 7,
             "name": 'Time Management',
             "description": 'Completes assigned tasks within defined timelines',
             "tool": 'Task tracking / delay analysis'},
            {"seq": 4, "weight": 8,
             "name": 'Office Maintenance',
             "description": 'Ensures timely repair and maintenance of office infrastructure',
             "tool": 'Management feedback'},
            {"seq": 5, "weight": 7,
             "name": 'Inventory Management',
             "description": 'Maintains adequate stock of office supplies and consumables',
             "tool": 'Management feedback'},
            {"seq": 6, "weight": 6,
             "name": 'Negotiation Skills',
             "description": 'Negotiates with vendors to achieve cost efficiency',
             "tool": 'Cost savings / management feedback'},
            {"seq": 7, "weight": 9,
             "name": 'Cost Control',
             "description": 'Monitors and controls administrative expenses',
             "tool": 'Management feedback'},
            {"seq": 8, "weight": 8,
             "name": 'Compliance & Safety',
             "description": 'Ensures office safety standards and administrative compliance',
             "tool": 'Management feedback'},
            {"seq": 9, "weight": 6,
             "name": 'Documentation',
             "description": 'Maintains proper records of admin activities and expenses',
             "tool": 'Documentation review'},
            {"seq": 10, "weight": 7,
             "name": 'Support to Departments',
             "description": 'Provides timely admin support to all departments',
             "tool": 'Internal feedback'},
            {"seq": 11, "weight": 5,
             "name": 'Event / Meetings Management',
             "description": 'Organizes office events and meetings smoothly',
             "tool": 'HR/ management feedback'},
            {"seq": 12, "weight": 9,
             "name": 'Work Quality',
             "description": 'Maintains accuracy and efficiency in admin tasks',
             "tool": 'Error rate / supervisor review'},
            {"seq": 13, "weight": 5,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 5,
             "name": 'Extra Responsibilities',
             "description": 'Takes initiative in handling additional admin work',
             "tool": 'Management feedback'},
        ],
    },
    {
        "key": 'ho-company-secretary',
        "name": 'Company Secretary',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Company Secretary', "department": 'Compliance'},
        ],
        "parameters": [
            {"seq": 1, "weight": 10,
             "name": 'Regulatory Compliance',
             "description": 'Ensures adherence to RBI/NBFC regulations and internal company policies',
             "tool": 'compliance checklist'},
            {"seq": 2, "weight": 8,
             "name": 'Policy Implementation',
             "description": 'Ensures effective implementation of company policies across branches',
             "tool": 'Field verification / management review'},
            {"seq": 3, "weight": 7,
             "name": 'Audit Coordination',
             "description": 'Coordinates internal and external audits efficiently',
             "tool": 'Management feedback'},
            {"seq": 4, "weight": 8,
             "name": 'Documentation Accuracy',
             "description": 'Maintains accurate and error-free compliance documentation',
             "tool": 'Document verification / audit findings'},
            {"seq": 5, "weight": 6,
             "name": 'Timely Reporting',
             "description": 'Submits compliance reports and returns within defined timelines',
             "tool": 'Submission timelines'},
            {"seq": 6, "weight": 9,
             "name": 'Risk Identification',
             "description": 'Identifies and reports potential compliance risks proactively',
             "tool": 'management feedback'},
            {"seq": 7, "weight": 5,
             "name": 'Discipline & Reliability',
             "description": 'Follows company discipline including dress code, punctuality, and professional behavior',
             "tool": 'Attendance, supervisor feedback'},
            {"seq": 8, "weight": 6,
             "name": 'Field Monitoring',
             "description": 'Conducts regular branch compliance checks',
             "tool": 'Management feedback'},
            {"seq": 9, "weight": 5,
             "name": 'Training & Awareness',
             "description": 'Provides training and updates to staff on compliance policies',
             "tool": 'Training records / feedback'},
            {"seq": 10, "weight": 5,
             "name": 'Coordination',
             "description": 'Coordinates effectively with Operations, Credit, and Accounts teams',
             "tool": 'Management feedback'},
            {"seq": 11, "weight": 7,
             "name": 'Continuous Improvement in Compliance Processes',
             "description": 'Suggests improvements to strengthen compliance framework',
             "tool": 'Improvements implemented / impact'},
            {"seq": 12, "weight": 10,
             "name": 'Work Quality',
             "description": 'Maintains high accuracy and quality in compliance work',
             "tool": 'Error rate / supervisor review'},
            {"seq": 13, "weight": 8,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 6,
             "name": 'Extra Responsibilities',
             "description": 'Willingly takes additional responsibilities as required',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'ho-ops-support-asst-manager',
        "name": 'Assistant Manager - Ops. Support',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Assistant Manager', "department": 'Operations'},
        ],
        "parameters": [
            {"seq": 1, "weight": 15,
             "name": 'TVR Quality & Accuracy',
             "description": 'Ensures correct and thorough tele verification of customers',
             "tool": 'Call audit score, verification accuracy %'},
            {"seq": 2, "weight": 8,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 3, "weight": 10,
             "name": 'Fake Case Identification',
             "description": 'Identifies suspicious/fraud cases during TVR',
             "tool": 'No. of fraud cases identified'},
            {"seq": 4, "weight": 10,
             "name": 'Field Support Effectiveness',
             "description": 'Provides timely and accurate support to field team',
             "tool": 'Feedback from field staff/BM'},
            {"seq": 5, "weight": 10,
             "name": 'Case Validation Accuracy',
             "description": 'Ensures correct validation before approval/disbursement',
             "tool": 'Error rate in verified cases'},
            {"seq": 6, "weight": 10,
             "name": 'Coordination with Branches & Departments',
             "description": 'Ensures smooth coordination with field, credit & accounts teams',
             "tool": 'Feedback from departments'},
            {"seq": 7, "weight": 8,
             "name": 'Data Entry & System Accuracy',
             "description": 'Maintains accurate data in system during/after TVR',
             "tool": 'System audit, error logs'},
            {"seq": 8, "weight": 5,
             "name": 'Documentation Check Support',
             "description": 'Verifies customer documents during process',
             "tool": 'Documentation audit score'},
            {"seq": 9, "weight": 5,
             "name": 'Query Handling (Field/Customer)',
             "description": 'Resolves queries from field/customers efficiently',
             "tool": 'Resolution time, feedback'},
            {"seq": 10, "weight": 5,
             "name": 'Productivity (Cases Handled)',
             "description": 'Number of TVR calls / cases handled daily',
             "tool": 'Daily productivity report'},
            {"seq": 11, "weight": 4,
             "name": 'Process Adherence (SOP)',
             "description": 'Follows defined scripts, policies, and RBI guidelines',
             "tool": 'Audit findings'},
            {"seq": 12, "weight": 4,
             "name": 'Training & Team Support',
             "description": 'Helps team members and shares knowledge',
             "tool": 'Management feedback'},
            {"seq": 13, "weight": 3,
             "name": 'Discipline & Reliability',
             "description": 'Follows company discipline including dress code, punctuality, and professional behavior',
             "tool": 'Attendance, supervisor feedback'},
            {"seq": 14, "weight": 3,
             "name": 'Extra Responsibilities',
             "description": 'Supports urgent work and additional responsibilities',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'ho-ops-support-deputy-manager',
        "name": 'Deputy Manager - Ops. Support',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Deputy Manager', "department": 'Operations'},
        ],
        "parameters": [
            {"seq": 1, "weight": 15,
             "name": 'Insurance & Accuracy',
             "description": 'Ensures correct and thorough tele verification of customers',
             "tool": 'Call audit score, verification accuracy %'},
            {"seq": 2, "weight": 8,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 3, "weight": 10,
             "name": 'Fake Case Identification',
             "description": 'Identifies suspicious/fraud cases during TVR',
             "tool": 'No. of fraud cases identified'},
            {"seq": 4, "weight": 10,
             "name": 'Field Support Effectiveness',
             "description": 'Provides timely and accurate support to field team',
             "tool": 'Feedback from field staff/BM'},
            {"seq": 5, "weight": 10,
             "name": 'Case Validation Accuracy',
             "description": 'Ensures correct validation before approval/disbursement',
             "tool": 'Error rate in verified cases'},
            {"seq": 6, "weight": 10,
             "name": 'Coordination with Branches & Departments',
             "description": 'Ensures smooth coordination with field, credit & accounts teams',
             "tool": 'Feedback from departments'},
            {"seq": 7, "weight": 8,
             "name": 'Data Entry & System Accuracy',
             "description": 'Maintains accurate data in system during/after TVR',
             "tool": 'System audit, error logs'},
            {"seq": 8, "weight": 5,
             "name": 'Documentation Check Support',
             "description": 'Verifies customer documents during process',
             "tool": 'Documentation audit score'},
            {"seq": 9, "weight": 5,
             "name": 'Query Handling (Field/Customer)',
             "description": 'Resolves queries from field/customers efficiently',
             "tool": 'Resolution time, feedback'},
            {"seq": 10, "weight": 5,
             "name": 'Productivity (Cases Handled)',
             "description": 'Number of TVR calls / cases handled daily',
             "tool": 'Daily productivity report'},
            {"seq": 11, "weight": 4,
             "name": 'Process Adherence (SOP)',
             "description": 'Follows defined scripts, policies, and RBI guidelines',
             "tool": 'Audit findings'},
            {"seq": 12, "weight": 4,
             "name": 'Training & Team Support',
             "description": 'Helps team members and shares knowledge',
             "tool": 'Management feedback'},
            {"seq": 13, "weight": 3,
             "name": 'Discipline & Reliability',
             "description": 'Follows company discipline including dress code, punctuality, and professional behavior',
             "tool": 'Attendance, supervisor feedback'},
            {"seq": 14, "weight": 3,
             "name": 'Extra Responsibilities',
             "description": 'Supports urgent work and additional responsibilities',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'ho-hr-asst-manager',
        "name": 'Assistant Manager - HR',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Assistant Manager', "department": 'Human Resources'},
        ],
        "parameters": [
            {"seq": 1, "weight": 10,
             "name": 'Recruitment & Hiring',
             "description": 'Ensures timely hiring as per manpower requirement',
             "tool": 'Hiring TAT / positions filled vs requirement'},
            {"seq": 2, "weight": 8,
             "name": 'Onboarding Process',
             "description": 'Smooth joining, documentation, and induction of new employees',
             "tool": 'Supervisor/Management feedback'},
            {"seq": 3, "weight": 8,
             "name": 'Attendance & Leave Management',
             "description": 'Accurate tracking of attendance and proper leave management',
             "tool": 'Management feedback'},
            {"seq": 4, "weight": 10,
             "name": 'Payroll Management',
             "description": 'Ensures timely and error-free salary processing',
             "tool": 'Management feedback'},
            {"seq": 5, "weight": 8,
             "name": 'Policy Implementation',
             "description": 'Ensures HR policies are properly implemented across organization',
             "tool": 'management feedback'},
            {"seq": 6, "weight": 7,
             "name": 'Employee Grievance Handling',
             "description": 'Resolves employee issues and concerns effectively',
             "tool": 'management feedback'},
            {"seq": 7, "weight": 7,
             "name": 'Performance Management (PMS)',
             "description": 'Manages appraisal process and performance tracking',
             "tool": 'PMS completion / review accuracy'},
            {"seq": 8, "weight": 9,
             "name": 'Documentation & Compliance',
             "description": 'Maintains employee records and ensures statutory compliance',
             "tool": 'Management feedback'},
            {"seq": 9, "weight": 6,
             "name": 'Exit Management',
             "description": 'Handles resignation, F&F, and exit formalities smoothly',
             "tool": 'Exit TAT / documentation accuracy'},
            {"seq": 10, "weight": 5,
             "name": 'Coordination',
             "description": 'Coordinates with all departments effectively',
             "tool": 'Management feedback'},
            {"seq": 11, "weight": 3,
             "name": 'TA/DA Verification',
             "description": 'Accurate and timely verification of employee TA/DA claims as per policy',
             "tool": 'Management feedback'},
            {"seq": 12, "weight": 10,
             "name": 'Work Quality',
             "description": 'Maintains accuracy and professionalism in HR tasks',
             "tool": 'Error rate / supervisor review'},
            {"seq": 13, "weight": 5,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 4,
             "name": 'Extra Responsibilities',
             "description": 'Takes initiative in handling additional HR tasks',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
    {
        "key": 'ho-it-executive',
        "name": 'Executive - IT',
        "narrative": 'ho',
        "applies_to": [
            {"designation": 'Executive', "department": 'IT'},
        ],
        "parameters": [
            {"seq": 1, "weight": 10,
             "name": 'System & Network Performance',
             "description": 'Ensures smooth functioning of CBS, LOS, network, and overall IT systems',
             "tool": 'Management feedback'},
            {"seq": 2, "weight": 8,
             "name": 'Issue Resolution (TAT & Quality)',
             "description": 'Resolves issues within defined time with accuracy',
             "tool": 'Team feedback'},
            {"seq": 3, "weight": 7,
             "name": 'Field Support',
             "description": 'Provides timely technical support to branches, BM, and field staff',
             "tool": 'Field team feedback'},
            {"seq": 4, "weight": 9,
             "name": 'Data Security',
             "description": 'Ensures data protection, access control, and confidentiality, regular data backups',
             "tool": 'Management feedback'},
            {"seq": 5, "weight": 6,
             "name": 'System Performance Optimization',
             "description": 'Improves system speed, performance, and reliability',
             "tool": 'Team feedback'},
            {"seq": 6, "weight": 6,
             "name": 'Attendance & Punctuality',
             "description": 'Follows company discipline including dress code, Maintains regular attendance and adheres to office timings consistently.',
             "tool": 'Feedback from Management and HR'},
            {"seq": 7, "weight": 8,
             "name": 'Innovation & Process Improvement',
             "description": 'Implements automation to reduce manual work and improve efficiency',
             "tool": 'Number of automations / time saved'},
            {"seq": 8, "weight": 9,
             "name": 'User Satisfaction Score',
             "description": 'Measures satisfaction level of internal users (branch staff, HO team)',
             "tool": 'Team feedback'},
            {"seq": 9, "weight": 6,
             "name": 'Team Collaboration',
             "description": 'Works effectively with internal teams & departments',
             "tool": 'Team / management feedback'},
            {"seq": 10, "weight": 5,
             "name": 'User Training & Support',
             "description": 'Trains and supports staff in using IT systems and tools',
             "tool": 'Training records / feedback'},
            {"seq": 11, "weight": 4,
             "name": 'Documentation',
             "description": 'Maintains proper records of issues, resolutions, and IT processes',
             "tool": 'Documentation review'},
            {"seq": 12, "weight": 5,
             "name": 'Work Quality',
             "description": 'Maintains accuracy in reports, configurations, and IT tasks',
             "tool": 'Management feedback'},
            {"seq": 13, "weight": 10,
             "name": 'Availability & Work Commitment',
             "description": 'Availability during urgent situations, support in extended hours',
             "tool": 'Management feedback'},
            {"seq": 14, "weight": 7,
             "name": 'Extra Responsibilities',
             "description": 'Takes initiative in handling additional tasks and urgent requirements',
             "tool": 'Supervisor/Management feedback'},
        ],
    },
]


def grade_for(score: float) -> tuple:
    """(grade, level) for a score out of 100. Fails closed on nonsense input."""
    if score is None or score < 0 or score > 100:
        return ("Invalid", "Invalid")
    for ceiling, grade, level in GRADE_BANDS:
        if score <= ceiling:
            return (grade, level)
    return ("Invalid", "Invalid")

